#ifndef QONVIFMANGER_GLOBAL_HPP
#define QONVIFMANGER_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(QONVIFMANGER_LIBRARY)
#  define QONVIFMANGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QONVIFMANGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QONVIFMANGER_GLOBAL_HPP
