#ifndef QONVIFMANAGER_GLOBAL_HPP
#define QONVIFMANAGER_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(QONVIFMANAGER_LIBRARY)
#  define QONVIFMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QONVIFMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QONVIFMANAGER_GLOBAL_HPP
